module Rbs
  module Src
    class Link
      attr_reader repo_url: String

      attr_reader base_path: Pathname

      attr_reader repository_prefix: Pathname

      attr_reader rbs_prefix: Pathname

      attr_reader gem_name: String

      attr_reader gem_version: String

      attr_reader force: bool

      attr_reader stdout: IO

      def initialize: (
        stdout: IO,
        repo_url: String,
        base_path: Pathname,
        repository_prefix: Pathname,
        rbs_prefix: Pathname,
        gem_name: String,
        gem_version: String,
        force: bool
      ) -> void

      def rbs_path: () -> Pathname

      def repository_path: () -> Pathname

      def repository_sig_path: () -> Pathname

      def run: () -> void

      def clean: () -> void

      def sh!: (*String, ?chdir: Pathname) -> void

      def clone_command: () -> Array[String]
    end
  end
end
